### ISSUE TITLE
Quick question about only scaling some tables

### ISSUE THREAD

**Issue by mcinteer** [channl/dynamodb-lambda-autoscale#11]
Hi there, I have a question around how you envisage people scaling only a set of tables. I have a number of dynamo tables and I just want a subset of them to use autoscaling. I've had a look through the code and I think the right place to filter the list of tables to scale is the [DynamoDB object](https://github.com/channl/dynamodb-lambda-autoscale/blob/master/src/DynamoDB.js#L23). 

Is this correct, or is there some other built in way that I could filter tables? 

Thanks in advance,
Ryan

**Comment by tmitchel2** [comment]
It's all driven by getTableUpdate() line 172 of Config.js.  If that function returns a null (which happens most of the time) then no update is performed.

I suggest you put your logic inside that by interrogating the 'description' parameter.

This does still however mean that it will request all table descriptions and then they are disregarded which isn't optimal if you just wanted to supply a hardcoded list of table names for example.  For that reason I'm going to leave this open and slightly modify the code to make this even easier.

**Comment by tmitchel2** [comment]
Config.js now includes a getTableNamesAsync arrow function which by default gets all the table names.  This is now the best place to adjust the set of tables which are within scope.  If you have any queries ill reopen.

**Comment by mcinteer** [comment]
Awesome, thanks very much @tmitchel2!

**Comment by tmitchel2** [comment]
Please get my very latest checkin which really improves the logging.  Also, please do let me know literally any likes / dislikes you have when testing.
