### ISSUE TITLE
[Feature Request] Different config for different tables :open_mouth: 

### ISSUE THREAD

**Issue by mcinteer** [channl/dynamodb-lambda-autoscale#12]
Hi there I've started using this and it works fantastically well. I thought I'd offer some insights as to how I'm using it and a potential feature.

I'm scaling a subset of my tables with this function. The way I'm doing that is by maintaining a tables-to-scale dynamo table that holds the names of the tables I want to scale. Our config then selects that list in the [getTableNamesAsync function](https://github.com/channl/dynamodb-lambda-autoscale/blob/master/src/Config.js#L278). This works well in that I don't need to update the code in order to add/remove tables we want to scale. 

What I have found though is that I want to scale the tables with different configuration. For example, I have 1 table that has enough load to warrant >1000 read throughput and another that barely reaches 5 read throughput. Ideally I would like to define a different scaling policy for each. 

If I were to implement this, then I think I'd try and keep the config next to the tablenames in the dynamo table I mentioned earlier. I wanted to check in with you before doing that though. Is this a usecase that you have thought about implementing and if so do you have any idea as to how you would do it?

Thanks again,
Ryan

**Comment by tmitchel2** [comment]
This is interesting, storing the simple part of that config in something like S3 or dynamodb is definitely something which I would like to make easier, especially table specific config.

In your case I suggest you try and store all your config against one key.  I do something similar on another project by having a Settings table and each key is the app name.

So I've actually already spent a bit of time refactoring the code to allow you to do this.  It's not complete yet but will be in the coming days.  Essentially a new function where you have to return the config based on a parameter containing table data. That then gets passed to the existing functions as a new parameter.

Out of curiosity how would you be changing the settings post table?

**Comment by mcinteer** [comment]
I think that for my tables with lower provisioned throughput (<50) I would want an adjustment percentage of 100% or more. But the tables that have a high level of throughput ( >500) I would want to have an adjustment percentage of 50-80% I think. This would be so that I don't increase the cost too much unnecessarily. 

I'd also like to set different min/max throughput per table. Some tables might have no reason to have large through put and if they do then I've got a bug somewhere. So limiting the scaling would add one guard against spending excessive money on dynamo tables.

**Comment by tmitchel2** [comment]
Explicit support for different config per table is coming very soon, please see https://github.com/channl/dynamodb-lambda-autoscale/issues/13 for an example of what the config will look like.

**Comment by tmitchel2** [comment]
Ok so I've pushed my latest to github.  The changes are quite extensive because i wanted to cater for most needs whilst keeping the codebase fairly simple.  Table level config is baked in now.  Please take a look at https://github.com/channl/dynamodb-lambda-autoscale/blob/master/src/Provisioner.js and the getTableConfig function.  At the moment it just returns a standard configuration.

The new provisioner configuration now supports different forms of increments / decrements without altering code.  You can increment by certain unit or percentage amounts, but more importantly you can increment / decrement 'to' a unit or percentage amount.  Which means you can increment immediately up to the required value rather than progressively 'climb' up.

Please take a quick look, as i mentioned i've not been able to test or document this extensively just yet but i wanted to get it out there....

**Comment by mjaverto** [comment]
@tmitchel2 I just found this project last night and must say I'm very happy to see this VS dynamic dynamo's approach to this issue. #12 was actually a huge limitation from us using this library so nice work. I plan on testing this weekend and will offer feedback.

**Comment by mcinteer** [comment]
Excellent, I've pulled your latest changes and can see exactly how to create config per table. I have found another problem which has me a little stumped but will open another issue. 

I can now do what I wanted from this issue, so I'll close it. Thanks again!
