### ISSUE TITLE
GetMetricStatistics returning 'unexpected' data

### ISSUE THREAD

**Issue by mcinteer** [channl/dynamodb-lambda-autoscale#15]
Hi again. 

Since I pulled down the latest changes to get the config per table I noticed that my tables have not been scaling up as I had expected so I did some digging and found the following on my DynamoDb metrics page. 
![image](https://cloud.githubusercontent.com/assets/2257651/16401883/2db6e714-3d3c-11e6-833c-8232f8b9f20e.png)

If I'm reading the [CapacityCalculatorBase](https://github.com/channl/dynamodb-lambda-autoscale/blob/master/src/capacity/CapacityCalculatorBase.js#L113-L124) correctly then it's getting the Average count which is always returning as `0.5` for me even when my consumed capacity is much higher. 

After this I went into Cloudwatch to try and explain what was going on and found that it was reporting consistent stats to that which the lambda was getting: 
![image](https://cloud.githubusercontent.com/assets/2257651/16401991/10c2f2c8-3d3d-11e6-8d02-f1084701fc4f.png)

I then went through the process of trying to work with the cloudwatch metrics and the formula talked about on the DynamoDb metrics page to turn the ConsumedReadCapacityUnits into something similar to what was being reported by the DynamoDb metrics. I found that if I changed what I queried in cloudwatch to `Sum` then it started making a bit more sense:

![image](https://cloud.githubusercontent.com/assets/2257651/16402051/7d574948-3d3d-11e6-8525-6e13bfaf6790.png)

`1,752/60` = `29.05`

And that marries up quite nicely with this number from my DynamoDb metrics:

![image](https://cloud.githubusercontent.com/assets/2257651/16402085/cda79e84-3d3d-11e6-93e9-726858801573.png)

One thing I don't understand is that I'm sure that the lambda was scaling my tables prior to pulling in the latest changes but from what I can see in your most recent commits, nothing around the cloudwatch metrics gathering changed.

So I think what I'm asking is, is this :bug: or am I doing something silly?

I'm happy to put together a fix and open a PR if this is in fact a bug, let me know.

Thanks,
Ryan

**Comment by mcinteer** [comment]
I ended up making the change in my fork, so opened up a [PR here ](https://github.com/channl/dynamodb-lambda-autoscale/pull/16)as well

**Comment by tmitchel2** [comment]
Thanks, I've merged the PR.

**Comment by tmitchel2** [comment]
Ok i've made some subtle changes on top of your PR
