### ISSUE TITLE
GSI issue with CapacityCalculatorBase.js

### ISSUE THREAD

**Issue by gump59** [channl/dynamodb-lambda-autoscale#19]
getDimensions(tableName: string, globalSecondaryIndexName: ?string): Dimension[] {
    if (globalSecondaryIndexName) {
      return [
        { Name: 'TableName', Value: tableName},
        { Name: 'GlobalSecondaryIndex', Value: globalSecondaryIndexName}
      ];
    }

```
return [ { Name: 'TableName', Value: tableName} ];
```

  }
}

Name for the GSI Dimension is slightly off, should be GlobalSecondaryIndexName instead of GlobalSecondaryIndex.  I haven't merged in your latest, but this bit is unchanged, and it was fixed when I changed it in my fork.

**Comment by tmitchel2** [comment]
I've made the change, many thanks for raising this.
