### ISSUE TITLE
Install steps produce failing lambda

### ISSUE THREAD

**Issue by steveparker-optimise** [channl/dynamodb-lambda-autoscale#2]
I followed the install instructions and that attached dist.zip was produced. This however fails on run with the following:

 "errorMessage": "Cannot find module 'winston'",

[dist.zip](https://github.com/channl/dynamodb-lambda-autoscale/files/274160/dist.zip)

**Comment by tmitchel2** [comment]
Hi Steve,

Are you running locally using npm run start or running on aws lambda?

When you run locally it will use the dist folder not the actual packaged zip.  Double check the Winston folder is there under dist/node_modules/winston.

If it is there then I think the directory you are running the npm run start from is not what I expect it to be which is the dynamodb-lambda-autoscale root folder.  Please see line 4 of /scripts/start.js to understand why the starting folder is expected to be the root one.

**Comment by steveparker-optimise** [comment]
Sorry should have been clearer. I'm only running it on AWS. My exact steps were:

Clone repo
CD to root directory
npm install
npm run build
upload dist.zip as a new function (with described role)

**Comment by steveparker-optimise** [comment]
If i cd into dist and run npm install there and then zip the folder contents - the lambda runs fine. The output is 20mb though.

**Comment by tmitchel2** [comment]
Let me take a look tonight once I get back to my mac.

**Comment by tmitchel2** [comment]
I think it's the permissions that have been set on your node_modules folder.  When I download and extract the zip onto my mac I can't even cd into the node_modules folder to see its content.  I presume aws lambda is having the same issue.  Im not sure why this would be the case, perhaps something todo with your default permissions?  Even if you can access the folder it might be that all other users cant..

Im contemplating removing the only node_module dependency (winston) anyway.

**Comment by brendonparker** [comment]
I also had some challenge getting this working when running locally using `npm start run`. Best I can tell, the `dotenv` package is failing to set the aws access keys. When I debug, it looks like any attempt to set `process.env` properties at run-time does nothing (doesn't throw an exception, but also doesn't set the value).

I'm running on Windows - don't know if that is to blame.

I was able to get it to work if I added the access keys to the `package.json` start script command.

**Comment by tmitchel2** [comment]
I think your issue is slightly different, I haven't tested windows compatibility.  It looks related to https://github.com/motdotla/dotenv/issues/83 and I've opened another issue to cover windows compatibility here https://github.com/channl/dynamodb-lambda-autoscale/issues/3

**Comment by tmitchel2** [comment]
I just made a commit https://github.com/channl/dynamodb-lambda-autoscale/commit/357123db0858a53be18ced5443bca6b86da4ef78 which removes all node_modules (i.e. winston) and changes the .env file to config.env.  This should sort both your issues.  Please let me know if you still get issues though as I haven't been able to test this on a windows machine.
