### ISSUE TITLE
Cannot read property 'histogram' of undefined

### ISSUE THREAD

**Issue by estahn** [channl/dynamodb-lambda-autoscale#23]
```
{
  "errorMessage": "Cannot read property 'histogram' of undefined",
  "errorType": "TypeError",
  "stackTrace": [
    "Object._callee2$ (/var/task/index.js:184:3414)",
    "tryCatch (/var/task/index.js:8381:41)",
    "GeneratorFunctionPrototype.invoke [as _invoke] (/var/task/index.js:8655:23)",
    "GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/var/task/index.js:8414:22)",
    "tryCatch (/var/task/index.js:8381:41)",
    "invoke (/var/task/index.js:8457:21)",
    "/var/task/index.js:8465:14",
    "run (/var/task/index.js:4904:23)",
    "/var/task/index.js:4917:29",
    "flush (/var/task/index.js:5287:10)"
  ]
}
```

**Comment by estahn** [comment]
I believe this has disappeared for some reason. I will reopen if this happens again.

**Comment by majodev** [comment]
Just encountered the same problem.

It looks like [`stJSON['DynamoDB.listTablesAsync'].histogram.mean`](https://github.com/channl/dynamodb-lambda-autoscale/blob/master/src/App.js#L168) is `undefined` if `getTableNamesAsync` inside `Provisioner.js` never actually calls [`this.db.listAllTableNamesAsync()`](https://github.com/channl/dynamodb-lambda-autoscale/blob/master/src/Provisioner.js#L23).

Easily reproducible by just synchronously returning an Array of qualifying table names there.

As an hacky workaround, one could simply call `const allTables = await this.db.listAllTableNamesAsync();` inside `getTableNamesAsync` without directly returning the values but so its side-effects can take place.

**Comment by tmitchel2** [comment]
I put a belt and braces change in which should fix the issue, please let me know if any issue persists.

**Comment by tmitchel2** [comment]
I put a belt and braces change in which should fix the issue, please let me know if any issue persists.
