### ISSUE TITLE
LimitExceededException: Subscriber limit exceeded: Only 10 tables can be created, updated, or deleted simultaneously

### ISSUE THREAD

**Issue by estahn** [channl/dynamodb-lambda-autoscale#24]
Issue with 10 or more tables to be updated. Tried to use something like `mapLimit` for 

```
let capacityTasks = tableNames
      .map(async tableName => {
```

but i'm not familiar with the babeljs stuff.

**Comment by tmitchel2** [comment]
Interesting, i didn't know this limit existed.  I'll patch this tonight.  Thanks for raising.

**Comment by estahn** [comment]
@tmitchel2 Great, looking forward to it. I will open up a pull request for fetching "all tables" as this has a limit too.

**Comment by estahn** [comment]
@tmitchel2 Any success in rate limiting this? Otherwise i just change it to all synchronous.

**Comment by tmitchel2** [comment]
Yes I've done most of it, couldn't figure out quite why it wasn't working and at the end of the evening remembered I needed to make follow up calls to describe table to get the status.  I've split out all the table updates into a new rate limited section.  Unfortunately waiting for the table updates to complete will incur some additional runtime but the waiting only kicks in if you need to update more than ten tables.  I think all of that makes it the most optimal....   I should get it fully complete today

**Comment by estahn** [comment]
Sounds great. I don't see any way around the additional runtime either, otherwise you won't be able to rate limit it.

**Comment by tmitchel2** [comment]
Ok this got a bit more involved than i had hoped!  Anyway, i think i have it working now and ive just checked it in.  I done some testing but please give is a good go to see if its working for you.  Please reopen straight away if there's an issue.

**Comment by estahn** [comment]
It runs successfully if i run it on my local but it doesn't seem to finish on time when running on Lambda.

```
2016-07-21T01:21:35.682Z    63281c86-4ee1-11e6-83d8-e5e9318c6581
{
    "errorMessage": "Connection timed out after 5000ms",
    "errorType": "TimeoutError",
    "stackTrace": [
        "ClientRequest.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/http/node.js:56:34)",
        "ClientRequest.g (events.js:260:16)",
        "emitNone (events.js:67:13)",
        "ClientRequest.emit (events.js:166:7)",
        "TLSSocket.emitTimeout (_http_client.js:533:10)",
        "TLSSocket.g (events.js:260:16)",
        "emitNone (events.js:67:13)",
        "TLSSocket.emit (events.js:166:7)",
        "TLSSocket.Socket._onTimeout (net.js:318:8)",
        "_runOnTimeout (timers.js:524:11)"
    ]
}
```

**Comment by estahn** [comment]
Never mind, i had to increase the memory limit for the lambda function which resolved the issue. Work nicely now. Great job!
