### ISSUE TITLE
Support windows OS when running locally

### ISSUE THREAD

**Issue by tmitchel2** [channl/dynamodb-lambda-autoscale#3]
Raised in response to https://github.com/channl/dynamodb-lambda-autoscale/issues/2

Looks like dotenv using a .env file is not supported on a windows OS as per https://github.com/motdotla/dotenv/issues/83

**Comment by tmitchel2** [comment]
https://github.com/channl/dynamodb-lambda-autoscale/commit/357123db0858a53be18ced5443bca6b86da4ef78 should have resolved this

**Comment by brendonparker** [comment]
Sorry for the delay. I was able that this fixed my issue on windows.
