### ISSUE TITLE
Trigger run via CloudWatch Event

### ISSUE THREAD

**Issue by estahn** [channl/dynamodb-lambda-autoscale#30]
Hi Guys,

We have occasional spikes that are only picked up after a minute. During this time we see failures due to underprovisioned capacity. Would there be any issues in using CloudWatch events to trigger the lambda script additionally to a time interval?

Enrico

**Comment by tmitchel2** [comment]
Im not sure if would help as the stats might not be available at such a recent time interval.  Also you could get issues as you can only make so many table updates concurrently, multiple concurrent lambda executions could mean it tries too many.  You could certainly experiment, however I think this pull request may help you https://github.com/channl/dynamodb-lambda-autoscale/pull/29

I will merge it in the coming days, it should mean a slight modification to the provisioner makes it better in this case.  A quick suggestion though, bring up a chart of that spike and overlay the throttled requests on it, if the throttled requests starts climbing before it auto scaled then I suspect it may help...
