### ISSUE TITLE
Decrement.By not working

### ISSUE THREAD

**Issue by Ralf-Te** [channl/dynamodb-lambda-autoscale#31]
Hello,

I'd like to scale a low number of dynamo-DB tables in a completely relative manner only setting boundaries by Min/Max Thresholds for read and write capacity.
The relative increment is working fine, but the relative decrement wouldn't simply decrement.
In the following I'd like to show u this just by changing definition of read-strategy.

Can you verify the issue or give me a hint if I am doing something wrong?

In (1) you can find the provisioner.json I intend to use. A run of it leads to the following result (recognize change wanted and allowed, but doing nothing):
> node ./scripts/start.js
*** LAMBDA INIT ***
*** LAMBDA START ***
Getting table names
Getting table details
Getting table description testtable
Getting table consumed capacity description testtable
Getting table update request testtable
testtable is consuming 0 of 410 (0%) read capacity units
testtable is consuming 0 of 410 (0%) read capacity units so a decrement is WANTED and is ALLOWED
testtable is consuming 0 of 200 (0%) write capacity units
testtable is consuming 0 of 200 (0%) write capacity units
Getting required table update requests
No table updates required
{
  "Index.handler": {
    "mean": 242.57998418807983
  },
  "DynamoDB.listTablesAsync": {
    "mean": 105.22508716583252
  },
  "DynamoDB.describeTableAsync": {
    "mean": 73.80222463607788
  },
  "DynamoDB.describeTableConsumedCapacityAsync": {
    "mean": 46.67149496078491
  },
  "CloudWatch.getMetricStatisticsAsync": {
    "mean": 40.9902560710907
  },
  "TableUpdates": {
    "count": 0
  },
  "TotalProvisionedThroughput": {
    "ReadCapacityUnits": 410,
    "WriteCapacityUnits": 200
  }
  "TotalMonthlyEstimatedCost": 131.976
}
*** LAMBDA FINISH ***

If I extend the provisioner.json from (1) with an Decrement.To to:
> ...   "Decrement": {
      "When": {
        "UtilisationIsBelowPercent": 50,
        "AfterLastIncrementMinutes": 60,
        "AfterLastDecrementMinutes": 60
      },
      "By": {
        "ConsumedPercent": 50
      },
      "To": {
        "Units": 200
      }

I get an successful update on the table as you can see in the following.
The Decrement done is a decrement to the value from the Decrement.To(200) and not a relative (should be 205). 
To be complete, if i remove the Decrement.By only having Decrement.To the run is also successful.

> node ./scripts/start.js
*** LAMBDA INIT ***
*** LAMBDA START ***
Getting table names
Getting table details
Getting table description testtable
Getting table consumed capacity description testtable
Getting table update request testtable
testtable is consuming 0 of 410 (0%) read capacity units
testtable is consuming 0 of 410 (0%) read capacity units so a decrement is WANTED and is ALLOWED
testtable is consuming 0 of 200 (0%) write capacity units
testtable is consuming 0 of 200 (0%) write capacity units
Getting required table update requests
Updating tables
Updating table testtable
Updated table testtable
Updated tables
{
  "Index.handler": {
    "mean": 336.56548500061035
  },
  "DynamoDB.listTablesAsync": {
    "mean": 114.78861999511719
  },
  "DynamoDB.describeTableAsync": {
    "mean": 66.52075910568237
  },
  "DynamoDB.describeTableConsumedCapacityAsync": {
    "mean": 56.809733867645264
  },
  "CloudWatch.getMetricStatisticsAsync": {
    "mean": 48.26799559593201
  },
  "TableUpdates": {
    "count": 1
  },
  "TotalProvisionedThroughput": {
    "ReadCapacityUnits": 410,
    "WriteCapacityUnits": 200
  },
  "TotalMonthlyEstimatedCost": 131.976
}

(1)
> {
  "ReadCapacity": {
    "Min": 200,
    "Max": 1000,
    "Increment": {
      "When": {
        "UtilisationIsAbovePercent": 70
      },
      "By": {
        "ConsumedPercent": 20
      }
    },
    "Decrement": {
      "When": {
        "UtilisationIsBelowPercent": 50,
        "AfterLastIncrementMinutes": 60,
        "AfterLastDecrementMinutes": 60
      },
      "By": {
        "ConsumedPercent": 50
      }
    }
  },
  "WriteCapacity": {
    "Min": 200,
    "Max": 500,
    "Increment": {
      "When": {
        "UtilisationIsAbovePercent": 70
      },
      "By": {
        "ConsumedPercent": 20
      }
    },
    "Decrement": {
      "When": {
        "UtilisationIsBelowPercent": 30,
        "AfterLastIncrementMinutes": 60,
        "AfterLastDecrementMinutes": 60
      },
      "By": {
        "ConsumedPercent": 50
      }
    }
  }

**Comment by Ralf-Te** [comment]
Hello,

I found the problem and of course it was a usage failure. 
What the provisioner.json above says is that a decrement should be done by 50% of the consumed capacity units. When one tests it with 0 capacity units consumed, one can not expect something to happen, because 50% of 0 is not a lot to decrement. :-(

**Comment by tmitchel2** [comment]
Ah yes, to be honest i didn't quite spot that myself.  I had decided to add a bit more logging in this area to help understand exactly what is going on and why.  Now i have an idea what extra logging is required.  Thanks.
