### ISSUE TITLE
the Right Way to extend getTableNamesAsync ?

### ISSUE THREAD

**Issue by keen99** [channl/dynamodb-lambda-autoscale#34]
as a non-developer - what's the right approach to extend `getTableNamesAsync` to treat it as config instead of code?

It seems like updating it in `src/Provisioner.js` gets the job done - but will make merging in upstream changes painful through the lifetime of support.

If there's a config oriented mechanism for extending this i'd love to hear about it and see some examples of it.   exploring forks of the project mostly seems to point to just changing the code in `Provisioner.js` is the common solution (for branches based off something like the current version, anyway)

**Comment by tmitchel2** [comment]
There's no real single right way, you could modify the code direct or store the config in a db or in a separate .js file.  I totally agree with your points but I don't have a better solution currently.
