### ISSUE TITLE
before/after TotalMonthlyEstimatedCost  ?

### ISSUE THREAD

**Issue by keen99** [channl/dynamodb-lambda-autoscale#35]
would it be possible to log both a before and after TotalMonthlyEstimatedCost?  From what I can tell, the TotalMonthlyEstimatedCost that's logged currently appears to be "current state"

could we also assemble a projected state (since we can't query it post update since updates dont apply immediately) and estimate a cost off of that?

Seems like it would be useful to see the projected cost before/after any particular update.

**Comment by keen99** [comment]
for that matter, a before/after TotalProvisionedThroughput would be a nice touch too..

**Comment by tmitchel2** [comment]
This is more like analytics which is much easier to integrate using a proper oss analytics package using all the raw data which this package outputs.  The projected cost is extremely rough as it literally only knows about that particular point in time.  For that matter aws charts based upon the actual dynamodb stats would be far better.
