### ISSUE TITLE
How to scale down working

### ISSUE THREAD

**Issue by dangvanthanh** [channl/dynamodb-lambda-autoscale#36]
This is my configure

```json
{
  "ReadCapacity": {
    "Min": 2,
    "Max": 20,
    "Increment": {
      "When": {
        "UtilisationIsAbovePercent": 90
      },
      "By": {
        "Units": 2
      },
      "To": {
        "ConsumedPercent": 110
      }
    },
    "Decrement": {
      "When": {
        "UtilisationIsBelowPercent": 30,
        "AfterLastIncrementMinutes": 60,
        "AfterLastDecrementMinutes": 60,
        "UnitAdjustmentGreaterThan": 2
      },
      "To": {
        "ConsumedPercent": 50
      }
    }
  }
}
```

When I set table in Dynamodb is 25. It will scale down 20. But from 20 it doesn't scale down to 2. I want to autoscale to min value if the table in Dynamo doesn't read any units. How to configure?

**Comment by tmitchel2** [comment]
Downscaling is rate limited by
1. the parameters you have set here, so 60 mins after the last increment and decrement, plus utilisation and min adjustment values as defined
2. a maximum of 4 decrements per day (imposed by aws), so it splits the remaining day into chunks so you don't use up your quota too soon and be stuck on a high rate.

I suspect its one of these but to work out exactly why it didnt drop you may need to debug through it, unfortunately the logging is not enough in all cases.  Closing for now but reopen if you feel there is certainly a bug.
