### ISSUE TITLE
No reaction on non-used system

### ISSUE THREAD

**Issue by uded** [channl/dynamodb-lambda-autoscale#4]
I think there is a logical problem with the behavior of default config. I have tried to deploy this code on system with no traffic at this point. The reaction of default `config.js` was to do nothing since all metrics returned `0` reads and `0` writes.

Maybe I am doing something wrong, but it seems like I cannot make this code to react on such system. I configured one table with read and writes values equals `10` and created 2 additional ones with default value (`5` for both). Still, nothing...

**Comment by tmitchel2** [comment]
Yes you're right.  I've made a change here https://github.com/channl/dynamodb-lambda-autoscale/commit/1a5440a1153aa84486e8b322213cd47e37a04397 so that it now respects a min value which is greater than 1.

Please let me know if you still get issues and i will reopen.
