### ISSUE TITLE
[Discussion] Strategy with fixed values.

### ISSUE THREAD

**Issue by cast** [channl/dynamodb-lambda-autoscale#40]
In order to accommodate multiple strategies for different tables/indexes I am proposing the following strategy schema update for fixed values:

ReadCapacity.Fixed: Number
WriteCapacity.Fixed: Number

The Provisioner.js file would have to be adapted, since there is quite some conditional logic on Read/WriteCapacity.Increment and Read/WriteCapacity.Increment.When.

Currently the following strategy would have to be set when using fixed values for specific tables/indexes without causing any errors in Provisioner.js:

```json
{
  "ReadCapacity": {
    "Min": 1,
    "Max": 1,
    "Increment":{
      "To": {
        "Units": 1
      },
      "When":{
      }
    },
    "Decrement":{
      "To": {
        "Units": 1
      },
      "When":{
      }
    }
  },
  "WriteCapacity": {
    "Min": 1,
    "Max": 1,
    "Increment":{
      "To": {
        "Units": 1
      },
      "When":{
      }
    },
    "Decrement":{
      "To": {
        "Units": 1
      },
      "When":{
      }
    }
  }
}
```

I'd be happy to add a pull request should this functionality be approved by more people/maintainer.

**Comment by tmitchel2** [comment]
You should just be able to specify the min and max to the same value and that's it, if that's not working then that would be a bug.  I don't think I would change it to fixed as it would only save a single line in that case... Am I understand you correctly?

**Comment by cast** [comment]
Hi Tom,

When you use the min and max values alone, no increment or decrements to that value are performed due to the following code blocks such as in the isReadCapacityIncrementRequired function in the Provisioner.js file line 50:

 ```javascript
if (config.ReadCapacity.Increment == null) {
      return false;
}
```

When adding an "Increment" or "Decrement" attrbute you also seem to need at least a "To" attribute and an empty "When" block. Otherwise either no change is performed or "not defined errors" occur.

**Comment by cast** [comment]
Small update, the minimum required configuration for a working fixed value currently is:

```json
{
  "ReadCapacity": {
    "Min": 1,
    "Max": 1,
    "Increment":{
      "When":{}
    },
    "Decrement":{
      "When":{}
    }
  },
  "WriteCapacity": {
    "Min": 1,
    "Max": 1,
    "Increment":{
      "When":{}
    },
    "Decrement":{
      "When":{}
    }
  }
}
```

**Comment by tmitchel2** [comment]
Ok that's a bug then, I'm making some other changes at the moment and I'll put a fix in for this also.  Thanks

**Comment by tmitchel2** [comment]
Just checked a fix, should work now
