### ISSUE TITLE
Table IOPS are currently being updated

### ISSUE THREAD

**Issue by dangvanthanh** [channl/dynamodb-lambda-autoscale#45]
I use dynamodb-lambda-autoscale but when table and global secondary indexes allow INCREMENT. But I see only global secondary indexes INCREMENT and capacity of table NOT INCREMENT. The occur I get from log

```json
Table IOPS are currently being updated
```

May I can INCREMENT table and global secondary indexes in this case.

**Comment by tmitchel2** [comment]
If you get that error it means something else is trying to update  the table provisioned through put.
