### ISSUE TITLE
Update packages

### ISSUE THREAD

**Issue by mamoit** [channl/dynamodb-lambda-autoscale#5]
I just ran npm install and I got these warnings.

```
npm WARN deprecated graceful-fs@3.0.8: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN deprecated lodash@1.0.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^4.0.0.
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
```

**Comment by tmitchel2** [comment]
These are indirect dependencies of libraries which I don't control.  I wouldn't want to cause more problems by potentially upgrading to newer versions of these unless there's a specific problem that you have hit?

**Comment by mamoit** [comment]
Well... It actually builds and does not log any errors.
So I guess that's not a real problem.
But it seems that it is not making any changes to the write capacity, even though I'm saturating it.
Any tips on what problem I may be running into?

**Comment by tmitchel2** [comment]
One raised issue is enough here.  I think you found the issue of the missed config settings, thanks for that.

**Comment by mamoit** [comment]
Indeed one was enough. Sorry for the spam, I reported everything that seemed unrelated, but apparently only one was an actual issue.
Thank you!
