### ISSUE TITLE
Missing script build in package.json

### ISSUE THREAD

**Issue by baconbyte** [channl/dynamodb-lambda-autoscale#58]
Following the instructions in the readme, when carrying out
`npm run build`
I'm getting this error
`npm ERR! missing script: build`
It looks like the package.json requires a build entry in the script section

**Comment by tmitchel2** [comment]
Whoops! I hadn't noticed, that was an accidental commit some time ago... i've been working on an experimental branch which has considerable changes but it looks like some if it got into main.  I've reverted the changes now so you should be alright.  Please reopen if you still have issues.

**Comment by baconbyte** [comment]
That sorted it - thanks
