### ISSUE TITLE
fsevents@1.0.12 not compatible with linux

### ISSUE THREAD

**Issue by mamoit** [channl/dynamodb-lambda-autoscale#6]
```
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.12
```

running `Linux 4.5.0-2-amd64 #1 SMP Debian 4.5.5-1 (2016-05-29) x86_64 GNU/Linux`

**Comment by tmitchel2** [comment]
fsevents is mac specific and an optional dependency.  It's a bad message by the sounds of it as per this issue https://github.com/npm/npm/issues/9204.  It can be ignored however if it's causing you an actual issue I can re-open.

**Comment by mamoit** [comment]
no actual issues seem to be caused by this.
