### ISSUE TITLE
0 read and write consumed capacity units

### ISSUE THREAD

**Issue by mamoit** [channl/dynamodb-lambda-autoscale#7]
I'm running in `eu-west-1`, and after debugging the `getTableUpdate` I wondered why I got 0 consumed write capacity units while I was writing to it at quite a high rate.
I'm not observing any automatic increase and I have two tables.

```
"tableConsumedCapacityDescription": {
  "Table": {
    "TableName": "test",
    "ConsumedThroughput": {
      "ReadCapacityUnits": 0,
      "WriteCapacityUnits": 0
    },
    "GlobalSecondaryIndexes": []
  }
}
```

**Comment by mamoit** [comment]
Maybe it's because there's no defined `thresholdPercent`in the `config.writeCapacity.increment`?

**Comment by tmitchel2** [comment]
Yes you are right, it was missing if the last refactor and would have affected that.  I've already commited a fix.  If it doesn't resolve you issue please let me know and Ill reopen.
