### ISSUE TITLE
npm run start fails due to case sensitivity

### ISSUE THREAD

**Issue by mamoit** [channl/dynamodb-lambda-autoscale#8]
I guess that you run this on mac, since by default HFS+ is case insensitive.
Since I'm running this on debian, `./scripts/start.js` and `./scripts/Start.js` are not the same thing.

**Comment by mamoit** [comment]
Same for `dist/index.js`, which `Start.js` expects to be `dist/Index.js`.

**Comment by tmitchel2** [comment]
Yes you're right I've only tested running locally on my Mac.  Unfortunately I don't have immediate access to a Linux machine so I'll just make the changes as and when you spot them.  I'll fix these couple up tonight.

**Comment by mamoit** [comment]
No hurries, no worries, those were the only two cases I encountered, I won't PR since I don't know if you'd prefer to rename the file or change the reference.

**Comment by tmitchel2** [comment]
Should be fixed in https://github.com/channl/dynamodb-lambda-autoscale/commit/4860600411cf273c7380407b4661beb7610dcfcf

Will reopen if you still have problems.
